config/routes.rb
Rails.application.routes.draw do

  root :to => 'moments#index'
  resources :moments

end

app/models/moment.rb
# == Schema Information
#
# Table name: moments
#
#  id            :integer          not null, primary key
#  post_author   :string
#  post_content  :text
#  post_image    :text
#  post_url      :text
#  post_medium   :string
#  post_location :string
#  post_date     :date
#  post_time     :time
#  created_at    :datetime
#  updated_at    :datetime
#

class Moment < ActiveRecord::Base

  def fetch_facebook_posts
  end

  def fetch_twitter_posts
  end

  def fetch_instagram_posts
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  def index
    @instagram_moments = InstagramMoment.new(lat, long, time).instagrams if params[:location]
    @twitter_moments = TwitterMoment.new(lat, long, bounds, time).tweets if params[:location]
  end

  private

  #a helper method means this method is available for use in the view 
  helper_method :moments, :rows, :instagram_moments, :twitter_moments

  def moments
    # In the case that @moments isn't assigned, create an empty array
    # so that our view .each method doesn't blow up.
    @moments = sort_moments((@instagram_moments || Array.new) + (@twitter_moments || Array.new))
  end

  def instagram_moments
    @instagram_moments
  end

  def twitter_moments
    @twitter_moments
  end

  def sort_moments(moments)
      moments.sort_by{|m|m[:post_datetime]}
  end

  def rows
    if moments.length > 0
      @moments.each_slice(5).to_a 
    else 
      Array.new
    end 
  end

  def location
    #if location is nil search with geocoder otherwise return the location 
    @location ||= Geocoder.search(params[:location]).first
  end

  def lat
    location.coordinates[0]
  end

  def long
    location.coordinates[1]
  end

  def southwest_bound_lng
    location.geometry["bounds"]["southwest"]["lng"]
  end

  def southwest_bound_lat
    location.geometry["bounds"]["southwest"]["lat"]
  end

  def northeast_bound_lng
    location.geometry["bounds"]["northeast"]["lng"]  
  end

  def northeast_bound_lat
    location.geometry["bounds"]["northeast"]["lat"]  
  end

  def bounds
    southwest_bound_lng.to_s + "," + southwest_bound_lat.to_s + "," + northeast_bound_lng.to_s + "," + northeast_bound_lat.to_s
  end

  def time
    Chronic.parse(params[:time])
  end
end

# when a request is made to the index action, the instagram moment is creates
# first it will look at the lat argument, and then go to the lat method
# the lat method calls the location method
# if there is no location, the location method requests the data from Google via geocoder
# and assigns the result to @location 
# it returns a geocoder object containing the data
# the lat method then calls .coordinates on the Geocoder object, 
# and accesses the first element to get the lat
# the new instagram moment repeats this process for long, 
# but when it hits the location method, the location is already stored, so there is no need
# for a second request to Google 

app/helpers/application_helper.rb
module ApplicationHelper
  def random_floating_image_class
    i = (1..10).to_a.sample
    "floating-image-#{i}"
  end

  def random_page_position
    top = rand(100..1000)
    left = rand(1..1000)
    "top: #{top}px; left: #{left}px;"
  end
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MomentInTime</title>
  	<script>window.twttr = (function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0],
	    t = window.twttr || {};
	  if (d.getElementById(id)) return t;
	  js = d.createElement(s);
	  js.id = id;
	  js.src = "https://platform.twitter.com/widgets.js";
	  fjs.parentNode.insertBefore(js, fjs);
	 
	  t._e = [];
	  t.ready = function(f) {
	    t._e.push(f);
	  };
	 
	  return t;
	}(document, "script", "twitter-wjs"));</script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= metamagic %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
<meta
  name="twitter:widgets:data-conversation"
  content="none">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moments/index.html.erb
<header>
	<h1 class="moment-in-time">moment in time</h1>
	<%= form_tag moments_path, class: "find-moments-form", method: :get do %>
	  <%= text_field_tag :time, nil, placeholder: 'eg. Two weeks ago' %>
	  <%= text_field_tag :location, nil, placeholder: 'eg. Bondi Beach' %>
	  <%= submit_tag 'Find moments', class: "find-btn" %>
	<% end %>
</header>
<section class="moments">
	<% rows.each do |row| %>
		<div class="row">
			<% row.each do |moment| %>
				<div style="<%= random_page_position %>" class="img-container <%= random_floating_image_class %>">
				  <% if moment[:source] == "instagram" %>

				  	<%= raw(moment[:oembed]["html"]) %>
				  	
				  <% elsif moment[:source] == "twitter" %>
				
					<%= raw(moment[:oembed][:html]) %>

				  <% end %>
				</div>
			<% end %>
		</div>
	<% end %>
</section>